name: main_branch_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make_module00_ex00
      run:  make -C module_00/ex00
    - name: make_module00_ex01
      run:  make -C module_00/ex01